/**
 * Download the base-set card art from the publisher's own server.
 *
 * The 2015/04 upload batch on starrealms.com is exactly the 49 base-set faces --
 * the 46 trade-deck cards plus Scout, Viper and Explorer -- at 724x1023 (ships)
 * and 1023x724 (bases). The WordPress REST API hands back a machine-readable
 * name -> URL map with per-image dimensions, unauthenticated.
 *
 * LEGAL: this art is (c) Wise Wizard Games and there is no fan-content licence.
 * Downloading it for a local, personal, non-distributed build is ordinary
 * personal use. The output directory is gitignored and must stay that way: do not
 * commit it, deploy it publicly, or package it. The game runs perfectly well
 * without any of these files -- missing art degrades to a procedural placeholder.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const HERE = dirname(fileURLToPath(import.meta.url))
const ART_DIR = join(HERE, '..', 'public', 'cards', 'art')
const MANIFEST = join(HERE, '..', 'src', 'cards', 'artManifest.gen.ts')

const API =
  'https://www.starrealms.com/wp-json/wp/v2/media' +
  '?per_page=100&media_type=image&after=2015-04-01T00:00:00&before=2015-05-01T00:00:00' +
  '&_fields=slug,title,source_url,media_details'

/**
 * Two publisher-side defects that a naive importer silently gets wrong.
 * Note also that URLs must come from `source_url` and never from slugifying the
 * name: 17 of the 49 files carry a WordPress `-e<epoch>` recrop suffix that
 * cannot be guessed.
 */
const TITLE_FIXES: Record<string, string> = {
  'Trading Port': 'trading-post', // the card is Trading POST
}

interface MediaItem {
  slug: string
  title: { rendered: string }
  source_url: string
  media_details?: { width?: number; height?: number }
}

function toCardId(title: string): string {
  const fixed = TITLE_FIXES[title]
  if (fixed) return fixed
  return title.toLowerCase().replace(/&#\d+;/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

const SIZES = [320, 640] as const

/**
 * The publisher serves COMPLETE CARD FACES, not isolated artwork -- frame, name
 * banner, cost, printed text and all. Layering our own frame over that produces
 * doubled text, so we crop the illustration band out of each scan and use only
 * that.
 *
 * Measured off the real scans: a ship's art runs from 13% to 65% of the card
 * height, a base's from 13% to 71%, both inset slightly from the printed border.
 */
const CROP = {
  portrait: { top: 0.143, height: 0.498, left: 0.032, width: 0.936 },
  landscape: { top: 0.150, height: 0.545, left: 0.030, width: 0.940 },
} as const

async function main(): Promise<void> {
  console.log('Fetching the card media index from starrealms.com ...')
  const res = await fetch(API)
  if (!res.ok) throw new Error(`WP REST API returned ${res.status}`)
  const items = (await res.json()) as MediaItem[]
  console.log(`  ${items.length} media items (expected 49)`)
  if (items.length !== 49) {
    console.warn(`  ! expected 49 base-set faces, got ${items.length} -- continuing anyway`)
  }

  await mkdir(ART_DIR, { recursive: true })
  await mkdir(dirname(MANIFEST), { recursive: true })

  const manifest: Record<string, { w: number; h: number; orientation: 'portrait' | 'landscape' }> = {}
  let ok = 0
  let failed = 0

  for (const item of items) {
    const id = toCardId(item.title.rendered)
    try {
      const imgRes = await fetch(item.source_url)
      if (!imgRes.ok) throw new Error(`HTTP ${imgRes.status}`)
      const buf = Buffer.from(await imgRes.arrayBuffer())
      const meta = await sharp(buf).metadata()
      const w = meta.width ?? 0
      const h = meta.height ?? 0

      const orientation = w >= h ? 'landscape' : 'portrait'
      const c = CROP[orientation]
      const box = {
        left: Math.round(w * c.left),
        top: Math.round(h * c.top),
        width: Math.round(w * c.width),
        height: Math.round(h * c.height),
      }
      for (const size of SIZES) {
        await sharp(buf).extract(box).resize({ width: size }).webp({ quality: 82 })
          .toFile(join(ART_DIR, `${id}-${size}.webp`))
      }
      manifest[id] = { w: box.width, h: box.height, orientation }
      ok++
      process.stdout.write(`  ${id.padEnd(20)} ${w}x${h} -> art ${box.width}x${box.height}\n`)
    } catch (err) {
      failed++
      console.warn(`  ! ${id}: ${(err as Error).message}`)
    }
  }

  const body = `// GENERATED by scripts/fetch-cards.ts -- do not edit.
//
// A missing card is simply an absent key: the renderer then falls back to its
// procedural placeholder, with no runtime 404 and no broken-image glyph.
export interface ArtEntry {
  /** Dimensions of the CROPPED illustration, not the source scan. */
  readonly w: number
  readonly h: number
  readonly orientation: 'portrait' | 'landscape'
}

export const ART_SIZES = [${SIZES.join(', ')}] as const

export const ART_MANIFEST: Readonly<Record<string, ArtEntry>> = ${JSON.stringify(manifest, null, 2)}

export function artUrl(cardId: string, size: (typeof ART_SIZES)[number] = 320): string | null {
  return ART_MANIFEST[cardId] ? \`/cards/art/\${cardId}-\${size}.webp\` : null
}
`
  await writeFile(MANIFEST, body, 'utf8')
  console.log(`\nDone: ${ok} downloaded, ${failed} failed.`)
  console.log(`Manifest -> ${MANIFEST}`)
  console.log('Reminder: public/cards/art/ is gitignored. Keep it that way.')
}

main().catch((err) => {
  console.error(err)
  process.exitCode = 1
})
