// GENERATED by scripts/fetch-cards.ts -- do not edit.
//
// Checked in EMPTY on purpose. The app imports this file, so a fresh clone must
// build without it having been generated; `npm run fetch-cards` fills it in
// locally. A card missing from the map is simply an absent key: no image request
// is made at all, and the renderer falls back to its procedural treatment.
//
// Regenerating it produces a local diff you are not expected to commit.
export interface ArtEntry {
  /** Dimensions of the CROPPED illustration, not the source scan. */
  readonly w: number
  readonly h: number
  readonly orientation: 'portrait' | 'landscape'
}

export const ART_SIZES = [320, 640] as const

export const ART_MANIFEST: Readonly<Record<string, ArtEntry>> = {}

export function artUrl(cardId: string, size: (typeof ART_SIZES)[number] = 320): string | null {
  return ART_MANIFEST[cardId] ? `/cards/art/${cardId}-${size}.webp` : null
}
